App redesign
windingtree/mvm-stats pull request #54
Opened 2018-04-14 07:32 UTC by skkr

This PR includes some design tweaks to be more aligned with the new branding guidelines, several improvements, updates to the style guide, and settings to make it a PWA.

@MatiasOS there were several conflicts, I double checked everything but please review it carefully just in case I missed something.

2018-04-16 16:58 UTC, MatiasOS requested changes

2018-04-16 16:58 UTC, MatiasOS commented on README.md
> +#### Deploy to Github Pages
We are no longer using Github Pages. Please, remove this lines

2018-04-17 13:45 UTC, MatiasOS approved these changes

2018-04-17 13:48 UTC, AugustoL approved these changes

2018-04-17 13:48 UTC, merged