Improved page 404 and implemented a different layout for it.
windingtree/mvm-stats pull request #8
Opened 2018-03-08 17:10 UTC by skkr

2018-03-08 18:01 UTC, AugustoL reviewed
@skkr please rebase with current master and resolve conflicts

2018-03-09 00:25 UTC, skkr commented
@AugustoL shoud be fine now.

2018-03-09 16:44 UTC, MatiasOS requested changes

2018-03-09 16:44 UTC, MatiasOS commented on src/layouts/LayoutError.js
> +    const self = this;
please, remove this assignment and  the few next

2018-03-09 16:44 UTC, MatiasOS commented on src/layouts/LayoutError.js
> +      _showAlert: (type, message) => self._alert.open(type, message)
please, extract  anon function outside the render method

2018-03-12 17:46 UTC, MatiasOS approved these changes
:+1:

2018-03-12 17:46 UTC, merged